#!/usr/bin/env python3
from __future__ import annotations

import argparse
import shutil
from pathlib import Path

from PIL import Image


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert a PNG frame sequence into a Plymouth script theme."
    )
    parser.add_argument("--frames-dir", type=Path, default=Path("frames"))
    parser.add_argument("--pattern", default="frame_*.png")
    parser.add_argument("--output-dir", type=Path, default=Path("plymouth-theme-kuleuven-punk"))
    parser.add_argument("--theme-name", default="kuleuven-punk")
    parser.add_argument("--fps", type=int, default=10)
    parser.add_argument("--background", default="0x000000")
    return parser.parse_args()


def collect_frames(frames_dir: Path, pattern: str) -> list[Path]:
    if not frames_dir.exists() or not frames_dir.is_dir():
        raise ValueError(f"Frames directory does not exist: {frames_dir}")
    frames = sorted(frames_dir.glob(pattern))
    if not frames:
        raise ValueError(f"No frames found in {frames_dir} with pattern '{pattern}'")
    return frames


def parse_background(background: str) -> tuple[float, float, float]:
    value = background.strip().lower()
    if value.startswith("0x"):
        value = value[2:]
    if value.startswith("#"):
        value = value[1:]
    if len(value) != 6:
        raise ValueError("--background must be a 6-digit RGB hex color (e.g. 0x000000)")

    try:
        red = int(value[0:2], 16)
        green = int(value[2:4], 16)
        blue = int(value[4:6], 16)
    except ValueError as err:
        raise ValueError("--background must be a valid hex color") from err

    return (red / 255.0, green / 255.0, blue / 255.0)


def generate_script(
    theme_name: str,
    frame_names: list[str],
    frame_width: int,
    frame_height: int,
    fps: int,
    background: str,
) -> str:
    if fps <= 0:
        raise ValueError("--fps must be greater than zero")

    background_red, background_green, background_blue = parse_background(background)

    # Plymouth refresh callback is often called at ~50 Hz.
    # Skipping callbacks lets us approximate the target FPS.
    updates_per_frame = max(1, round(50 / fps))

    frame_lines = "\n".join(
        f'frames[{index}] = Image("{name}");' for index, name in enumerate(frame_names)
    )

    return f"""# Auto-generated by generate_plymouth_theme.py
Window.SetBackgroundTopColor({background_red:.6f}, {background_green:.6f}, {background_blue:.6f});
Window.SetBackgroundBottomColor({background_red:.6f}, {background_green:.6f}, {background_blue:.6f});

frame_count = {len(frame_names)};
frame_index = 0;
refresh_tick = 0;
updates_per_frame = {updates_per_frame};

{frame_lines}

sprite = Sprite();
sprite.SetImage(frames[0]);
sprite.SetZ(10000);
sprite.SetX(Window.GetX() + (Window.GetWidth(0) / 2 - {frame_width} / 2));
sprite.SetY(Window.GetY() + (Window.GetHeight(0) / 2 - {frame_height} / 2));

fun refresh_callback ()
  {{
    refresh_tick = refresh_tick + 1;
    if ((refresh_tick % updates_per_frame) != 0)
      return;

    frame_index = frame_index + 1;
    if (frame_index >= frame_count)
      frame_index = 0;

    sprite.SetImage(frames[frame_index]);
  }}

Plymouth.SetRefreshFunction(refresh_callback);
"""


def generate_plymouth_file(theme_name: str) -> str:
    return f"""[Plymouth Theme]
Name={theme_name}
Description=Animated boot theme generated from frame sequence
ModuleName=script

[script]
ImageDir=/usr/share/plymouth/themes/{theme_name}
ScriptFile=/usr/share/plymouth/themes/{theme_name}/{theme_name}.script
"""


def main() -> None:
    args = parse_args()
    frames = collect_frames(args.frames_dir, args.pattern)

    first_image = Image.open(frames[0]).convert("RGBA")
    frame_width, frame_height = first_image.size

    args.output_dir.mkdir(parents=True, exist_ok=True)

    copied_names: list[str] = []
    for index, frame_path in enumerate(frames):
        copied_name = f"frame_{index:04d}.png"
        copied_names.append(copied_name)
        shutil.copy2(frame_path, args.output_dir / copied_name)

    script_content = generate_script(
        theme_name=args.theme_name,
        frame_names=copied_names,
        frame_width=frame_width,
        frame_height=frame_height,
        fps=args.fps,
        background=args.background,
    )
    script_path = args.output_dir / f"{args.theme_name}.script"
    script_path.write_text(script_content, encoding="utf-8")

    plymouth_content = generate_plymouth_file(args.theme_name)
    plymouth_path = args.output_dir / f"{args.theme_name}.plymouth"
    plymouth_path.write_text(plymouth_content, encoding="utf-8")

    print(f"Wrote Plymouth theme to {args.output_dir}")
    print(f"- {script_path.name}")
    print(f"- {plymouth_path.name}")
    print(f"- {len(copied_names)} frames")


if __name__ == "__main__":
    main()
