#!/usr/bin/env python3
from __future__ import annotations

import argparse
import shutil
from pathlib import Path

from PIL import Image


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert a PNG frame sequence into a Plymouth script theme."
    )
    parser.add_argument("--frames-dir", type=Path, default=Path("frames"))
    parser.add_argument("--pattern", default="frame_*.png")
    parser.add_argument(
        "--output-dir", type=Path, default=Path("plymouth-theme-kuleuven-punk")
    )
    parser.add_argument("--theme-name", default="kuleuven-punk")
    parser.add_argument("--fps", type=int, default=10)
    parser.add_argument("--background", default="0x000000")
    parser.add_argument("--runtime-themes-dir", default="/run/plymouth/themes")
    return parser.parse_args()


def collect_frames(frames_dir: Path, pattern: str) -> list[Path]:
    if not frames_dir.exists() or not frames_dir.is_dir():
        raise ValueError(f"Frames directory does not exist: {frames_dir}")
    frames = sorted(frames_dir.glob(pattern))
    if not frames:
        raise ValueError(f"No frames found in {frames_dir} with pattern '{pattern}'")
    return frames


def parse_background(background: str) -> tuple[float, float, float]:
    value = background.strip().lower()
    if value.startswith("0x"):
        value = value[2:]
    if value.startswith("#"):
        value = value[1:]
    if len(value) != 6:
        raise ValueError("--background must be a 6-digit RGB hex color (e.g. 0x000000)")

    try:
        red = int(value[0:2], 16)
        green = int(value[2:4], 16)
        blue = int(value[4:6], 16)
    except ValueError as err:
        raise ValueError("--background must be a valid hex color") from err

    return (red / 255.0, green / 255.0, blue / 255.0)


def generate_script(
    theme_name: str,
    frame_names: list[str],
    frame_width: int,
    frame_height: int,
    fps: int,
    background: str,
) -> str:
    if fps <= 0:
        raise ValueError("--fps must be greater than zero")

    background_red, background_green, background_blue = parse_background(background)

    # Plymouth refresh callback is often called at ~50 Hz.
    # Skipping callbacks lets us approximate the target FPS.
    updates_per_frame = max(1, round(25 / fps))

    frame_lines = "\n".join(
        f'frames[{index}] = Image("{name}");' for index, name in enumerate(frame_names)
    )

    return f"""# Auto-generated by generate_plymouth_theme.py
Window.SetBackgroundTopColor({background_red:.6f}, {background_green:.6f}, {background_blue:.6f});
Window.SetBackgroundBottomColor({background_red:.6f}, {background_green:.6f}, {background_blue:.6f});

frame_count = {len(frame_names)};
frame_index = 0;
refresh_tick = 0;
updates_per_frame = {updates_per_frame};

{frame_lines}

sprite = Sprite();
sprite.SetZ(-10000);
sprite.SetX(Window.GetX());
sprite.SetY(Window.GetY());

screen_width = Window.GetWidth(0);
screen_height = Window.GetHeight(0);
sprite.SetImage(frames[0].Scale(screen_width, screen_height));
progress_track_pixel = Image("progress_track_pixel.png");
progress_fill_pixel = Image("progress_fill_pixel.png");

progress_bar_max_width = Math.Int(screen_width * 0.56);
if (progress_bar_max_width < 260)
  progress_bar_max_width = 260;
progress_bar_height = 10;
progress_bar_x = Window.GetX() + (Window.GetWidth() - progress_bar_max_width) / 2;
progress_bar_y = Window.GetY() + Window.GetHeight() - 252;

fun refresh_callback ()
  {{
    refresh_tick = refresh_tick + 1;
    if ((refresh_tick % updates_per_frame) != 0)
      return;

    frame_index = frame_index + 1;
    if (frame_index >= frame_count)
      frame_index = 0;

    sprite.SetImage(frames[frame_index].Scale(screen_width, screen_height));
  }}

Plymouth.SetRefreshFunction(refresh_callback);

global.password_prompt = Sprite();
global.password_bullets = Sprite();
global.status_sprite = Sprite();
global.progress_track_sprite = Sprite();
global.progress_fill_sprite = Sprite();
global.progress_percent_sprite = Sprite();
global.previous_prompt = "";
global.previous_bullets = 0;

progress_track_sprite.SetImage(progress_track_pixel.Scale(progress_bar_max_width, progress_bar_height));
progress_track_sprite.SetPosition(progress_bar_x, progress_bar_y, 18980);

progress_fill_sprite.SetImage(progress_fill_pixel.Scale(1, progress_bar_height));
progress_fill_sprite.SetPosition(progress_bar_x, progress_bar_y, 18985);

fun display_normal_callback ()
  {{
    password_prompt.SetImage(Image());
    password_bullets.SetImage(Image());
  }}

fun update_status_callback (text)
  {{
    if (text == "")
      {{
        status_sprite.SetImage(Image());
        return;
      }}

    status_image = Image.Text(text, 1, 1, 1);
    status_x = Window.GetX() + (Window.GetWidth() - status_image.GetWidth()) / 2;
    status_y = Window.GetY() + Window.GetHeight() - 220;

    status_sprite.SetImage(status_image);
    status_sprite.SetPosition(status_x, status_y, 19000);
  }}

fun boot_progress_callback (duration, progress)
  {{
    normalized_progress = progress;
    if (normalized_progress < 0)
      normalized_progress = 0;
    if (normalized_progress > 1)
      normalized_progress = 1;

    fill_width = Math.Int(progress_bar_max_width * normalized_progress);
    if (fill_width < 1)
      fill_width = 1;

    progress_fill_sprite.SetImage(progress_fill_pixel.Scale(fill_width, progress_bar_height));
    progress_fill_sprite.SetPosition(progress_bar_x, progress_bar_y, 18985);

    percent_text = "" + Math.Int(normalized_progress * 100) + "%";
    percent_image = Image.Text(percent_text, 1, 1, 1);
    percent_x = Window.GetX() + (Window.GetWidth() - percent_image.GetWidth()) / 2;
    percent_y = progress_bar_y - 28;

    progress_percent_sprite.SetImage(percent_image);
    progress_percent_sprite.SetPosition(percent_x, percent_y, 18990);
  }}

fun display_password_callback (prompt, bullets)
  {{
    prompt_text = prompt;
    if (prompt_text == "")
      prompt_text = "Passphrase:";

    if ((bullets == 0) && (previous_bullets > 0) && (prompt_text == previous_prompt))
      prompt_text = "Unlocking...";

    bullet_text = "";
    for (index = 0; index < bullets; index++)
      bullet_text = bullet_text + "*";

    prompt_image = Image.Text(prompt_text, 1, 1, 1);
    bullets_image = Image.Text(bullet_text, 1, 1, 1);

    prompt_x = Window.GetX() + (Window.GetWidth() - prompt_image.GetWidth()) / 2;
    prompt_y = Window.GetY() + Window.GetHeight() - 160;
    bullets_x = Window.GetX() + (Window.GetWidth() - bullets_image.GetWidth()) / 2;
    bullets_y = prompt_y + 40;

    password_prompt.SetImage(prompt_image);
    password_prompt.SetPosition(prompt_x, prompt_y, 20000);

    password_bullets.SetImage(bullets_image);
    password_bullets.SetPosition(bullets_x, bullets_y, 20000);

    previous_prompt = prompt_text;
    previous_bullets = bullets;
  }}

Plymouth.SetDisplayNormalFunction(display_normal_callback);
Plymouth.SetDisplayPasswordFunction(display_password_callback);
Plymouth.SetUpdateStatusFunction(update_status_callback);
Plymouth.SetBootProgressFunction(boot_progress_callback);
"""


def generate_plymouth_file(theme_name: str, runtime_themes_dir: str) -> str:
    theme_dir = f"{runtime_themes_dir.rstrip('/')}/{theme_name}"
    return f"""[Plymouth Theme]
Name={theme_name}
Description=Animated boot theme generated from frame sequence
ModuleName=script

[script]
ImageDir={theme_dir}
ScriptFile={theme_dir}/{theme_name}.script
"""


def main() -> None:
    args = parse_args()
    frames = collect_frames(args.frames_dir, args.pattern)

    first_image = Image.open(frames[0]).convert("RGBA")
    frame_width, frame_height = first_image.size

    args.output_dir.mkdir(parents=True, exist_ok=True)

    copied_names: list[str] = []
    for index, frame_path in enumerate(frames):
        copied_name = f"frame_{index:04d}.png"
        copied_names.append(copied_name)
        shutil.copy2(frame_path, args.output_dir / copied_name)

    progress_track_pixel_path = args.output_dir / "progress_track_pixel.png"
    progress_track_pixel = Image.new("RGBA", (1, 1), (0, 0, 0, 192))
    progress_track_pixel.save(progress_track_pixel_path)

    progress_fill_pixel_path = args.output_dir / "progress_fill_pixel.png"
    progress_fill_pixel = Image.new("RGBA", (1, 1), (255, 255, 255, 244))
    progress_fill_pixel.save(progress_fill_pixel_path)

    script_content = generate_script(
        theme_name=args.theme_name,
        frame_names=copied_names,
        frame_width=frame_width,
        frame_height=frame_height,
        fps=args.fps,
        background=args.background,
    )
    script_path = args.output_dir / f"{args.theme_name}.script"
    script_path.write_text(script_content, encoding="utf-8")

    plymouth_content = generate_plymouth_file(args.theme_name, args.runtime_themes_dir)
    plymouth_path = args.output_dir / f"{args.theme_name}.plymouth"
    plymouth_path.write_text(plymouth_content, encoding="utf-8")

    print(f"Wrote Plymouth theme to {args.output_dir}")
    print(f"- {script_path.name}")
    print(f"- {plymouth_path.name}")
    print(f"- {len(copied_names)} frames")


if __name__ == "__main__":
    main()
